# Generated by Django 4.2.20 on 2025-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_deliveryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='pin_code',
            field=models.CharField(max_length=20),
        ),
    ]
