# Generated by Django 4.2.20 on 2025-04-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_deliveryinfo_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
