# Generated by Django 4.2.20 on 2025-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_deliveryinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='payment_method',
            field=models.CharField(default='upi', max_length=50),
        ),
    ]
