# Generated by Django 4.2.20 on 2025-05-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_posterslide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosterSlide',
            new_name='Slide',
        ),
    ]
